anomaly_clean: false
batch_size: 16
data_type: molecule
epochs: 40
freeze_layers: embed_tokens,gbf,gbf_proj,encoder.layers.0,encoder.layers.1,encoder.layers.2,encoder.layers.3
freeze_layers_reversed: false
kfold: 1
learning_rate: 2.0e-05
load_model_dir: null
logger_level: 1
max_epochs: 100
max_norm: 5.0
metrics: mae
model_name: unimolv1
model_size: 84m
num_classes: 2
patience: 8
remove_hs: false
seed: 42
smi_strict: true
smiles_col: SMILES
split: scaffold
split_group_col: scaffold
split_method: 1fold_scaffold
split_seed: 42
target_col_prefix: TARGET
target_cols: hepg2_pIC50,hct116_pIC50
target_normalize: auto
task: multilabel_regression
use_amp: true
use_cuda: true
use_ddp: false
use_gpu: all
warmup_ratio: 0.03
